class_view/urls.py
from django.urls import re_path, include
from django.views.generic import  TemplateView
from . import views

app_name='class_view'

urlpatterns = [
    re_path(r'^', include([
        re_path(r'^$', views.index, name='index'),
        re_path(r'^template-views/$', TemplateView.as_view(template_name='class_view/template.html'), name='template_views'),
        re_path(r'^about/$', views.AboutTemplateVies.as_view(), name='about'),
        re_path(r'^head/$', views.HeadTemplateList.as_view(), name='head'),
    ]))
]

first_step/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^quik-guide/', include('quik_guide.urls')),
    re_path(r'^polls/', include('polls.urls')),
    re_path(r'^class-view/', include('class_view.urls')),
]

polls/urls.py
from django.urls import re_path, include
from . import views

app_name = 'polls'
urlpatterns = [
    re_path(r'^$', views.IndexView.as_view(), name='index'),
    re_path(r'^(?P<pk>[\d]+)/', include([
        re_path(r'^$', views.detail, name='detail'),
        re_path(r'^result/$', views.result, name='result'),
        re_path(r'^vote/$', views.vote, name='vote')
    ]))
]

quik_guide/urls.py
from django import views
from django.urls import re_path, include
from . import views

urlpatterns = [
    re_path(r'^$', views.main, name='quik-guide'),
    re_path(r'^news/$', views.news, name='news'),
    re_path(r'^articles/', include([
        re_path(r'^$', views.article, name='article'),
        re_path(r'^(?P<year>[\d]{4})/', include([
            re_path(r'^$', views.year, name='year'),
            re_path(r'^(?P<mount>[\d]{1,2})/', include([
                re_path(r'^$', views.mount, name='mount'),
                re_path(r'^(?P<id>[\d]+)/$', views.id, name='article_detail'),
            ]))
        ])),
    ])),
]

class_view/models.py
from django.db import models

# Create your models here.

polls/models.py
from datetime import timedelta

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - timedelta(days=1)

class Choise(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choise_text = models.CharField(max_length=100)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choise_text
    

quik_guide/models.py
from statistics import mode
from django.db import models

# Create your models here.

class Reporter(models.Model):
    full_name = models.CharField(max_length=70)

    def __str__(self):
        return self.full_name

class Article(models.Model):
    pub_date = models.DateTimeField()
    headline = models.CharField(max_length=100)
    content = models.TextField()
    reporter = models.ForeignKey(Reporter, on_delete=models.CASCADE)

    def __str__(self):
        return self.headline

class_view/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import TemplateView, ListView
from django.template import loader
from django.urls import reverse
from polls.models import Question
import requests

# Create your views here.

def index(request):
    return HttpResponse('Hello im index page')

class AboutTemplateVies(TemplateView):
    template_name = 'class_view/about.html'

    def get(self, request, *args, **kwargs):
        return HttpResponse(render(request, 'class_view/get.html'))

    def post(self, request, *args, **kwargs):
        return HttpResponse(loader.get_template('class_view/post.html').render())

class HeadTemplateList(ListView):
    template_name = 'class_view/head.html'
    model = Question


    def get(self, request, *args, **kwargs):
        question = Question.objects.all()
        head = requests.head('http://127.0.0.1:8000/class-view/head/')
        return render(request, 'class_view/head.html', {'question_list': question, 'head': head})

    def head(self, request):
        
        return HttpResponse('Hi ima head response')

polls/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from .models import Question, Choise


# Create your views here.

# def index(request):
#     '''
#     Page views list of questions
#     '''
#     q_list = Question.objects.order_by('-pub_date')[:5]
#     content = {'q_list': q_list}
#     i_template = loader.get_template('polls/index.html')
#     return HttpResponse(i_template.render(content, request))


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'q_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')


def detail(request, pk):
    try:
        question = Question.objects.get(id=pk)
    except Question.DoesNotExist:
        raise Http404('Заданный опрос не найден')
        content = {'content': question}
        return render(request, 'polls/detail.html', content)
    question = get_object_or_404(Question, id=pk)
    return render(request, 'polls/detail.html', {'question': question})


def result(request, pk):
    question = get_object_or_404(Question, pk=pk)
    return render(request, 'polls/result.html', {'question': question})

def vote(request, pk):
    question = get_object_or_404(Question, pk=pk)
    try:
        choise = question.choise_set.get(pk=request.POST['choice'])
    except (KeyError, Choise.DoesNotExist):
        error_message = 'Необходимо выбрать один из вариантов'
        return HttpResponseRedirect(reverse('polls:detail', args=(question.id,)), {'questionw': question, 'error_message': error_message})
    else:
        choise.votes += 1
        choise.save()
        return HttpResponseRedirect(reverse('polls:result', args=(question.id,)))

quik_guide/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Article

# Create your views here.

def main(request):
    a_list = Article.objects.order_by('-pub_date')
    return render(request, 'quik_guide/main.html', {'articles': a_list})

def news(request):
    return HttpResponse('This news page')

def article(request):
    return HttpResponse('This article page')

def year(request, year):
    a_list = Article.objects.filter(pub_date__year=year)
    context = {'year': year, 'a_list': a_list}
    return render(request, 'quik_guide/year_archive.html', context)

def mount(requst, year, mount):
    return HttpResponse(f'This {year} {mount} article page')

def id(requst, year, mount, id):
    return HttpResponse(f'This article {id} publishec {mount}:{year}')

class_view/templates/class_view/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello i'am about page</h1>
    <h2>{% block page_text %}{% endblock page_text %}</h2>
</body>
</html>

class_view/templates/class_view/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}{% endblock content %}
</body>
</html>

class_view/templates/class_view/get.html
{% extends 'class_view/about.html' %}

{% block page_text %}
    <h1>Get request call this page</h1>
{% endblock page_text %}

class_view/templates/class_view/head.html
{% extends 'class_view/base.html' %}

{% block content %}
    <h1>Question List</h1>
    {{ question }}
    <ul>
    {% for one_q in question_list.all %}
            <li>{{ one_q }} Опубликовано: {{ one_q.pub_date }}</li>
    {% endfor %}
    </ul>
    <h1>Head request</h1>
    <p>{{ head }}</p>
{% endblock content %}

class_view/templates/class_view/post.html
{% extends 'class_view/about.html' %}

{% block page_text %}
    <h1>Post request call this page</h1>
{% endblock page_text %}

class_view/templates/class_view/template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hi, am TemplateView!!!</h1>
    <a href="{% url 'class_view:about' %}">Get About Page</a>
    <form action="{% url 'class_view:about' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Post About Page">
    </form>
    
</body>
</html>

polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    {% block content %}{% endblock content %}
</body>
</html>

polls/templates/polls/detail.html
{% extends 'quik_guide/base.html' %}

{% block title %}{{ question.question_text|truncatechars:'10' }}{% endblock title %}

{% block content %}
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>
            <h1>{{ question.question_text }}</h1>
        </legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choise_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choise_text }}</label><br>
        {% endfor %}
        <label for=""></label>
    </fieldset>
    <input type="submit" value="Vote">
</form>
{% endblock content %}

polls/templates/polls/index.html
{% extends 'quik_guide/base.html' %}

{% block title %}Опросы{% endblock title %}

{% block content %}
{% if q_list %}
    {% for question in q_list %}
    <ul>
        <li><a href=" {% url 'polls:index' %}{{ question.id }}/">{{ question.question_text }}</a></li>
    </ul>
    {% endfor %}
{% else %}
    <h3>В последнее время небыло опросов</h3>
{% endif %}

{% endblock content %}

polls/templates/polls/result.html
{% extends 'quik_guide/base.html' %}

{% block title %}Результаты голосования{% endblock title %}

{% block content %}
    <h1>На вопрос: {{ question.question_text }}</h1>
    <ul>
        {% for choise in question.choise_set.all %}
            <li>{{ choise.choise_text }} Проголосовало {{ choise.votes }} человек</li>
        {% endfor %}
    </ul>
    <a href="{% url 'polls:vote' question.id %}">Проголосовать снова?</a>
{% endblock content %}

quik_guide/templates/quik_guide/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <a href="{% url 'polls:index' %}">
        <img src="{% static 'quik_guide/logo.png' %}" alt="Logo">    
    </a>
    {% block content %}{% endblock content %}
</body>
</html>

quik_guide/templates/quik_guide/main.html
{% load extratags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Новостной блог</h1>
    {% regroup articles by pub_date  as datearticles%}
    {% for datearticle in datearticles %}
        {% now "DATE_FORMAT" as currentdate %}
        {% if datearticle.grouper|date:'DATE_FORMAT'  == currentdate %}
            {% comment %}
                Выводит новости за сегодняшний день
            {% endcomment %}
            <h4>За сегодня</h4>
            {% for article in datearticle.list %}
                <h2>{{ article.headline|title }}</h1>
                <h5>{{ article.pub_date|date:'G:i' }} {{ article.reporter }}</h5>
                <p>{{ article.content }}</p>
            {% endfor %}
        {% else %}
            {% for article in datearticle.list %}
                <h2>{{ article.headline|title }}</h1>
                <h5>{{ article.pub_date|date:'j F Y' }} {{ article.reporter|title }}</h5>
                <p>{{ article.content }}</p>
            {% endfor %}
        {% endif %}
    {% endfor %}
</body>
</html>

quik_guide/templates/quik_guide/news.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for article in articles %}
        <h2>{{ article.headline }}</h1>
        <h4>{{ acticle.pub_date }} {{ article.reporter }}</h4>
        <p>{{ article.content }}</p>
    {% endfor %}
</body>
</html>

quik_guide/templates/quik_guide/year_archive.html
{% extends "quik_guide/base.html" %}

{%block title %}Articles for {{ year }}{% endblock %}

{% block content %}
<h1>Articles for {{ year }}</h1>

{% for article in a_list %}
    <p>{{ article.headline }}</p>
    <p>By {{ article.reporter.full_name }}</p>
    <p>Published {{ article.pub_date|date:'F j, Y' }}</p>
    <p>{{ article.content }}</p>
{% endfor %}
{% endblock %}